name: reloh
description: A Chess Clock
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  msgpack_dart: ^1.0.1
  shared_preferences: ^2.0.17
  duration_picker: "^1.0.0"
  audioplayers: ^3.0.1
  url_launcher: ^6.1.9

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/PretendardVariable.ttf

  assets:
    - assets/audio/click.mp3
